mVoxApp.Web/Controllers/ChampionshipController.cs
using mVoxApp.Web.App_Data.Repository;
using mVoxApp.Web.Controllers.BLL;
using mVoxApp.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mVoxApp.Web.Controllers
{
    public class ChampionshipController : Controller
    {
        ManagerTeamStaticRepository _mngerTeam = new ManagerTeamStaticRepository();
        ManagerKeyGroupStaticRepository _mngerKey = new ManagerKeyGroupStaticRepository();


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult Tables()
        {
            //Teams    
            List<TeamModel> _listTeams = _mngerTeam.GetAll().OrderBy(x => x.Id).ToList();            

            //Keygroup  
            List<KeyGroupModel> _listKeygroups = _mngerKey.GetAll().OrderBy(x=>x.Id).ToList();        

            /*      +----------------------------------+
                    |              VIEWDATA            |
                    +----------------------------------+
            */                        
            for (int i = 1; i <= _listKeygroups.Count; i++)
            {
                //DETALHES DOS GRUPOS - TABELA PRINCIPAL TOPO
                ViewData[$"TeamsByKeyGroup{i}"] = _listTeams.FindAll(x => x.KeyGroup == (i-1)).ToList();

                //Count TotalTeams -> KeyGroup                
                int qtdd = _mngerTeam.CountByKeyGroup(i - 1);
                _listKeygroups[i - 1].TotalTeams = qtdd;

                //NOMES DAS TABELAS DE CLASSIFICAÇÃO
                ViewData[$"KeyGroupName{i}"] = _listKeygroups[i-1].Name;
            }

            ViewData["teams-all"] = _listTeams;
            ViewData[$"keygroups-all"] = _listKeygroups;
            ViewData[$"KeyGroups"] = _listKeygroups;                                    

            return View("Tables", _listTeams);
        }

        public ActionResult WonGame(int id)
        {
            try
            {
                TeamModel _team = _mngerTeam.GetByID(id);
                int nextKeyGroup = _team.KeyGroup + 1;

                if (!_mngerKey.KeyGroupFull(nextKeyGroup))
                {
                    _team.KeyGroup = _team.KeyGroup + 1;                    
                    _mngerTeam.Update(_team);
                }
                else
                {
                    ViewBag.alert = "Alert";
                }
                ViewBag.alert2 = "Alert2";

                return RedirectToAction("Tables");
            }
            catch
            {
                return View("Error");
            }
        }        

        public ActionResult NotCreated()
        {
            return View("NotCreated");
        }

        /* 
                +---------------------------------------------------------------+
                |                           CRUD                                |
                +---------------------------------------------------------------+
        */
        // GET: Championship/Details/5
        public ActionResult Details(int id)
        {
            TeamModel team = _mngerTeam.GetByID(id);
            return View(team);
        }
        
        // GET: Championship/Details/5
        public ActionResult DeleteFromKeyGroup(int id)
        {
            try
            {
                TeamModel _team = _mngerTeam.GetByID(id);
                _team.KeyGroup = 0;

                _mngerTeam.Update(_team);
                return RedirectToAction("Tables");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Championship/Create
        public ActionResult Create()
        {
            List<TeamModel> listReturn = _mngerTeam.GetAll().OrderBy(x => x.Id).ToList();
            ViewData["TeamList"] = listReturn;
            
            return View("Register");
        }

        // POST: Championship/Create
        [HttpPost]
        public ActionResult Create(TeamModel _team)
        {
            try
            {
                _mngerTeam.Create(_team);
                
                //ViewBag.Msg = "Criado Com Sucesso";

                return View("Index");
            }
            catch
            {
                //ViewBag.Msg = "Erro ao Tentar Criar";
                return View("Error");
            }
        }

        // GET: Championship/Edit/5
        public ActionResult Edit(int id)
        {
            TeamModel retorno = _mngerTeam.GetByID(id);
            return View("Edit", retorno);
        }

        // POST: Championship/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TeamModel _team)
        {
            try
            {
                _mngerTeam.Update(_team);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Championship/Search
        public ActionResult Search()
        {
            return View("Search");
        }

        // POST: Championship/Search
        [HttpPost]
        public ActionResult Search(TeamModel busca)
        {
            try
            {
                List<TeamModel> ListaBuscada = _mngerTeam.GetByName(busca.Name);
                ViewData["SearchPView"] = ListaBuscada;

                return View("Search");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Championship/Delete/5
        public ActionResult Delete(int id)
        {
            TeamModel retorno = _mngerTeam.GetByID(id);
            return View("Delete", retorno);            
        }

        // POST: Championship/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, TeamModel _team)
        {
            try
            {
                _mngerTeam.Delete(id);
                return RedirectToAction("Create");
            }
            catch
            {
                return View();
            }
        }

        
        

    }
}

mVoxApp.Web/Views/Shared/NotCreated.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width" />
    <title>Erro</title>
</head>
<body>
    <hgroup>
        <h1>Não Criada.</h1>
        <h2>A página que você está procurando ainda não foi implementada.</h2>
    </hgroup>
</body>
</html>

mVoxApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Championship Control", "Index", "Championship", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Championship")</li>
                    <li>@Html.ActionLink("Registrados", "Create", "Championship")</li>
                    <li>@Html.ActionLink("Tabelas", "Tables", "Championship")</li>
                    <li>@Html.ActionLink("Chaves[Modelo]", "NotCreated", "Championship")</li>
                    <li>@Html.ActionLink("Busca", "Search", "Championship")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Championship")</li>
                    <li>@Html.ActionLink("Contact-me", "Contact", "Championship")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
            <p>Alex+Silva - Feito com C# e ♥  |  github:alexssantos </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>